### ISSUE TITLE
Hello, may i have contact.

### ISSUE THREAD

**Issue by amanuel2** [primis/Apollo#1]
Hello, im asking for contact to meet with you about OS Development. If you can reply to me we can talk about this. Thankyou. (For Github Staffs : This is not a silly issue, im asking for contact to participate in github.)

**Comment by primis** [comment]
You can email me<nick@primis.org>if you wanna talk

**Comment by amanuel2** [comment]
Or can you go here @primis ? https://kobra.io/#/e/-KMI3WcxjDRp7FaqGH18 . Tell me when your there :) .

**Comment by amanuel2** [comment]
Or can you go here @primis ? https://kobra.io/#/e/-KMI3WcxjDRp7FaqGH18 . Once your there can you notify me here? Thankyou! :) . (Im on now)

**Comment by primis** [comment]
I'm sorry, what's the point of this? Without an actual issue to discuss, this belongs on private email (see comment above).

**Comment by amanuel2** [comment]
Im Inside Kobra. Talk to me there. you will see why @primis

**Comment by primis** [comment]
I'm there.

**Comment by amanuel2** [comment]
Im Back There Sorry @primis
