### ISSUE TITLE
[reopen please] Could Apollo currently fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [primis/Apollo#3]
_**Not sure why my previous issue was closed... Sorry friend but it was not a spam,
I am just trying to find the perfect OS that could fit on a floppy and be quite useful...
Also, it is sad for me to see that your last commit was 1 year ago, perhaps
I could try contributing to your project, but only if it fits on a floppy of course ;)**_

Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by primis** [comment]
Honestly, Apollo can fit on a floppy, but it was never designed for that. Apollo's stagnation is probably also indefinite, due to a personal change. If anyone would want to submit push requests, feel free to. Closing this as non-issue.
