### ISSUE TITLE
Error booting 'Apollo OS' 0.0.2 floppy in QEMU

### ISSUE THREAD

**Issue by informer2016** [primis/Apollo#4]
Dear @primis , first of all thank you very much for releasing Apollo OS as a floppy _(which could be installed in coreboot/SeaBIOS ROM and booted from there)_ But before doing that I tried booting your [0.0.2 floppy](https://github.com/primis/Apollo/archive/0.0.2.zip) in QEMU with the following command:
`qemu-system-x86_64 -L . -m 256 -fda ./floppy.img -usbdevice tablet -vga vmware -localtime`
and only see
```
GRUB Loading stage2.........
Press 'ESC' to enter the menu... 0
```
followed by
```
Booting 'Apollo OS'

root (fd0)
 Filesystem type is fat, using whole disk
kernel /Apollo/sys.mod
```
and after that QEMU reboots. If there is a way to collect more debug information, please tell me and I will try to provide it

**Comment by primis** [comment]
The floppy image is outdated. It needs to be updated

**Comment by informer2016** [comment]
@primis Would be nice if you could make a new release, then I could test it, maybe as a part of BIOS if it works in QEMU

**Comment by informer2016** [comment]
@primis Happy coming New Year ! :christmas_tree: :santa: :gift:

**Comment by primis** [comment]
Floppy image (bin/floppy.img) is now current image and will continue to be updated regularly -- Closing Issue.
